os: osx 
language: generic
osx_image: xcode13.1
before_script:
 - travis_wait brew update
 #- travis_wait brew install --HEAD usbmuxd
 #- travis_wait brew unlink usbmuxd
 #- travis_wait brew link usbmuxd
 - brew install libplist || echo 'fails because libimobiledevice-glue is missing'
 - git clone https://github.com/libimobiledevice/libimobiledevice-glue.git
 - cd libimobiledevice-glue
 - ./autogen.sh
 - make
 - sudo make install
 - cd ..
 - travis_wait brew install --HEAD libimobiledevice
 - travis_wait brew install ideviceinstaller
 - travis_wait brew install ios-deploy
 - travis_wait git clone https://github.com/flutter/flutter.git -b beta --depth 1
script: 
 - flutter/bin/flutter build ios --debug --no-codesign
before_cache:
 - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then brew cleanup; fi
 # Credit https://discourse.brew.sh/t/best-practice-for-homebrew-on-travis-brew-update-is-5min-to-build-time/5215/9
 # Cache only .git files under "/usr/local/Homebrew" so "brew update" does not take 5min every build
 - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then find /usr/local/Homebrew \! -regex ".+\.git.+" -delete; fi
cache: 
  directories: 
  - $HOME/.pub-cache
  - $HOME/Library/Caches/Homebrew
  - /usr/local/Homebrew
before_deploy: 
  - pushd build/ios/iphoneos 
  - mkdir Payload 
  - cd Payload 
  - ln -s ../Runner.app 
  - cd .. 
  - zip -r app.ipa Payload 
  - popd