os: osx 
language: generic
osx_image: xcode8.3
before_script:
 - travis_wait brew update
 - travis_wait brew install --HEAD usbmuxd
 - travis_wait brew unlink usbmuxd
 - travis_wait brew link usbmuxd
 - travis_wait brew install --HEAD libimobiledevice
 - travis_wait brew install ideviceinstaller
 - travis_wait brew install ios-deploy
 - travis_wait git clone https://github.com/flutter/flutter.git -b beta --depth 1
script: 
 - flutter/bin/flutter build ios --debug --no-codesign
cache: 
  directories: 
  - $HOME/.pub-cache
before_deploy: 
  - pushd build/ios/iphoneos 
  - mkdir Payload 
  - cd Payload 
  - ln -s ../Runner.app 
  - cd .. 
  - zip -r app.ipa Payload 
  - popd